// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPo7oxumegWXnmBlSkcCvxQLyVL_JBAv0',
    appId: '1:786178836835:web:a9f0295455f983476aeb56',
    messagingSenderId: '786178836835',
    projectId: 'money-traking-678b4',
    authDomain: 'money-traking-678b4.firebaseapp.com',
    storageBucket: 'money-traking-678b4.firebasestorage.app',
    measurementId: 'G-TPM80B0FQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3cinRZIDHhELqS0weeAAtBGiHpPu3yz8',
    appId: '1:786178836835:android:3402d7fbc8b170c66aeb56',
    messagingSenderId: '786178836835',
    projectId: 'money-traking-678b4',
    storageBucket: 'money-traking-678b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj71ovwbO5TOLL46kw8nNWSOK1cIRAiPM',
    appId: '1:786178836835:ios:68e8504f53f5b5fc6aeb56',
    messagingSenderId: '786178836835',
    projectId: 'money-traking-678b4',
    storageBucket: 'money-traking-678b4.firebasestorage.app',
    iosClientId: '786178836835-p7obnhj3fgcckid90v6da6qdga209pl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );
}
