import 'package:get_it/get_it.dart';


final getIt = GetIt.instance;

void configureDependencies() {
  // TODO: Run 'dart run build_runner build' to generate dependency injection code
  // getIt.init(); // Generated by injectable package
}
